#[cfg(all(target_os = "windows", not(test)))]
fn main() {
    // The complete GPUI layout stack (including debug-mode builder temporaries)
    // exceeds the MSVC 1 MiB default for expanded settings. Reserve address space
    // only for the UI executable; committed pages still grow on demand.
    if std::env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc") {
        println!("cargo:rustc-link-arg-bin=devmanager=/STACK:8388608");
    }
    emit_preview_build_identity();
    emit_shipping_build_identity();
    generate_provider_catalog_typescript_mirror();
    validate_web_bundle();
    stamp_windows_binaries();
}

#[cfg(not(target_os = "windows"))]
fn main() {
    emit_preview_build_identity();
    emit_shipping_build_identity();
    generate_provider_catalog_typescript_mirror();
    validate_web_bundle();
}

fn emit_preview_build_identity() {
    let identity = std::env::var("DEV_MANAGER_PREVIEW_BUILD_IDENTITY")
        .unwrap_or_else(|_| "unbound".to_string());
    if identity != "unbound"
        && (identity.len() != 64 || !identity.bytes().all(|byte| byte.is_ascii_hexdigit()))
    {
        panic!("DEV_MANAGER_PREVIEW_BUILD_IDENTITY must be a 64-character hexadecimal digest");
    }
    println!("cargo:rustc-env=DEV_MANAGER_PREVIEW_BUILD_IDENTITY={identity}");
    println!("cargo:rerun-if-env-changed=DEV_MANAGER_PREVIEW_BUILD_IDENTITY");
}

fn emit_shipping_build_identity() {
    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".to_string());
    let shipping = format!("devmanager/{version}");
    let host = format!("devmanager-host/{version}");
    let ctl = format!("devmanager-host-ctl/{version}");
    println!("cargo:rustc-env=DEVMANAGER_SHIPPING_IDENTITY={shipping}");
    println!("cargo:rustc-env=DEVMANAGER_HOST_BUILD_IDENTITY={host}");
    println!("cargo:rustc-env=DEVMANAGER_CTL_BUILD_IDENTITY={ctl}");
    println!("cargo:rerun-if-env-changed=CARGO_PKG_VERSION");
    println!("cargo:rerun-if-changed=packaging/package-contract.json");
}

fn generate_provider_catalog_typescript_mirror() {
    use std::fs;
    use std::path::PathBuf;

    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let seeds_path = manifest_dir.join("src/ui/provider_catalog_seeds.rs");
    println!("cargo:rerun-if-changed={}", seeds_path.display());
    let raw = fs::read_to_string(&seeds_path)
        .unwrap_or_else(|error| panic!("read {}: {error}", seeds_path.display()));
    let reviewed = extract_rust_str_const(&raw, "CATALOG_REVIEWED_AT")
        .unwrap_or_else(|| panic!("CATALOG_REVIEWED_AT missing from {}", seeds_path.display()));
    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from src/ui/provider_catalog_seeds.rs — do not edit.\n");
    out.push_str(&format!("// Reviewed at: {reviewed}\n\n"));
    out.push_str("import type { WebAiKind } from \"../../api/types\";\n");
    out.push_str("import type {\n");
    out.push_str("  SlashCommand,\n");
    out.push_str("  SlashCommandCategory,\n");
    out.push_str("  SlashCommandInteraction,\n");
    out.push_str("  SlashCommandSuggestion,\n");
    out.push_str("} from \"./types\";\n\n");
    out.push_str(&format!(
        "export const BUILTIN_CATALOG_REVIEWED_AT = \"{reviewed}\";\n\n"
    ));
    out.push_str("type Seed = readonly [\n");
    out.push_str("  name: `/${string}`,\n");
    out.push_str("  description: string,\n");
    out.push_str("  options?: {\n");
    out.push_str("    category?: SlashCommandCategory;\n");
    out.push_str("    argumentHint?: string;\n");
    out.push_str("    suggestions?: readonly SlashCommandSuggestion[];\n");
    out.push_str("    aliases?: readonly string[];\n");
    out.push_str("    interaction?: SlashCommandInteraction;\n");
    out.push_str("  },\n");
    out.push_str("];\n\n");
    out.push_str(
        "function suggestionsFromHint(hint: string | undefined): SlashCommandSuggestion[] {\n",
    );
    out.push_str("  if (!hint?.includes(\" | \")) return [];\n");
    out.push_str("  return hint.split(\" | \").map((value) => ({\n");
    out.push_str("    label: value.charAt(0).toUpperCase() + value.slice(1),\n");
    out.push_str("    value,\n");
    out.push_str("  }));\n");
    out.push_str("}\n\n");
    out.push_str(
        "function catalog(provider: WebAiKind, seeds: readonly Seed[]): SlashCommand[] {\n",
    );
    out.push_str("  return seeds.map(([name, description, options]) => ({\n");
    out.push_str("    name,\n");
    out.push_str("    description,\n");
    out.push_str("    provider,\n");
    out.push_str("    source: \"builtin\",\n");
    out.push_str("    category: options?.category ?? \"workflow\",\n");
    out.push_str("    argumentHint: options?.argumentHint ?? null,\n");
    out.push_str(
        "    suggestions: [...(options?.suggestions ?? suggestionsFromHint(options?.argumentHint))],\n",
    );
    out.push_str("    aliases: [...(options?.aliases ?? [])],\n");
    out.push_str("    interaction: options?.interaction ?? \"inline\",\n");
    out.push_str("  }));\n");
    out.push_str("}\n\n");
    append_rust_seed_block(&mut out, "CLAUDE_SEEDS", &raw);
    out.push('\n');
    append_rust_seed_block(&mut out, "CODEX_SEEDS", &raw);
    out.push('\n');
    out.push_str("export const CLAUDE_BUILTIN_COMMANDS = catalog(\"claude\", CLAUDE_SEEDS);\n");
    out.push_str("export const CODEX_BUILTIN_COMMANDS = catalog(\"codex\", CODEX_SEEDS);\n");
    let dest = manifest_dir.join("web/src/tasks/commands/builtinCatalog.generated.ts");
    write_if_changed(&dest, out.as_bytes());
}

fn write_if_changed(path: &std::path::Path, contents: &[u8]) {
    let unchanged = std::fs::read(path)
        .ok()
        .is_some_and(|current| current == contents);
    if !unchanged {
        std::fs::write(path, contents)
            .unwrap_or_else(|error| panic!("write {}: {error}", path.display()));
    }
}

fn extract_rust_str_const(source: &str, name: &str) -> Option<String> {
    let marker = format!("pub const {name}: &str = \"");
    let start = source.find(&marker)? + marker.len();
    let end = source[start..].find('"')? + start;
    Some(source[start..end].to_string())
}

fn append_rust_seed_block(out: &mut String, name: &str, source: &str) {
    let marker = format!("pub const {name}: &[CatalogSeed] = &[");
    let start = source
        .find(&marker)
        .unwrap_or_else(|| panic!("{name} missing from provider_catalog_seeds.rs"));
    let mut depth = 1usize;
    let mut index = start + marker.len();
    let bytes = source.as_bytes();
    while index < bytes.len() && depth > 0 {
        match bytes[index] {
            b'[' => depth += 1,
            b']' => depth -= 1,
            _ => {}
        }
        index += 1;
    }
    let body = &source[start + marker.len()..index.saturating_sub(1)];
    out.push_str(&format!("const {name}: readonly Seed[] = [\n"));
    for chunk in body.split("CatalogSeed {").skip(1) {
        let Some(end) = chunk.find("},") else {
            continue;
        };
        let block = &chunk[..end];
        let command = rust_field_str(block, "command").expect("command");
        let description = rust_field_str(block, "description").expect("description");
        let mut opts = Vec::new();
        if let Some(category) = rust_option_str(block, "category") {
            opts.push(format!("category: \"{category}\""));
        }
        if let Some(hint) = rust_option_str(block, "argument_hint") {
            let escaped = hint.replace('\\', "\\\\").replace('"', "\\\"");
            opts.push(format!("argumentHint: \"{escaped}\""));
        }
        if let Some(aliases_body) = rust_slice_body(block, "aliases") {
            let aliases = rust_str_list(aliases_body);
            if !aliases.is_empty() {
                let joined = aliases
                    .into_iter()
                    .map(|alias| format!("\"{alias}\""))
                    .collect::<Vec<_>>()
                    .join(", ");
                opts.push(format!("aliases: [{joined}]"));
            }
        }
        if block.contains("opens_provider_menu: true") {
            opts.push("interaction: \"providerMenu\"".to_string());
        }
        let escaped = description.replace('\\', "\\\\").replace('"', "\\\"");
        if opts.is_empty() {
            out.push_str(&format!("  [\"{command}\", \"{escaped}\"],\n"));
        } else {
            out.push_str(&format!(
                "  [\"{command}\", \"{escaped}\", {{ {} }}],\n",
                opts.join(", ")
            ));
        }
    }
    out.push_str("];\n");
}

fn rust_field_str(block: &str, field: &str) -> Option<String> {
    let marker = format!("{field}: \"");
    let start = block.find(&marker)? + marker.len();
    let end = block[start..].find('"')? + start;
    Some(block[start..end].to_string())
}

fn rust_option_str(block: &str, field: &str) -> Option<String> {
    let some_marker = format!("{field}: Some(\"");
    if let Some(start_rel) = block.find(&some_marker) {
        let start = start_rel + some_marker.len();
        let end = block[start..].find('"')? + start;
        return Some(block[start..end].to_string());
    }
    None
}

fn rust_slice_body<'a>(block: &'a str, field: &str) -> Option<&'a str> {
    let marker = format!("{field}: &[");
    let start = block.find(&marker)? + marker.len();
    let end = block[start..].find(']')? + start;
    Some(&block[start..end])
}

fn rust_str_list(body: &str) -> Vec<String> {
    let mut values = Vec::new();
    let mut rest = body;
    while let Some(start_rel) = rest.find('"') {
        let start = start_rel + 1;
        let Some(end_rel) = rest[start..].find('"') else {
            break;
        };
        let end = start + end_rel;
        values.push(rest[start..end].to_string());
        rest = &rest[end + 1..];
    }
    values
}

#[cfg(all(target_os = "windows", not(test)))]
fn stamp_windows_binaries() {
    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".to_string());
    let (major, minor, patch, build) = windows_file_version_parts(&version);
    println!("cargo:rerun-if-changed=packaging/icons/devmanager.ico");
    println!("cargo:rerun-if-changed=packaging/package-contract.json");

    // Keep winresource on the Windows build graph for SDK discovery compatibility.
    // Per-binary VERSIONINFO must use cargo:rustc-link-arg-bin=<name>=... (via embed-resource).
    let _ = winresource::WindowsResource::new();

    stamp_windows_binary(
        "devmanager",
        "DevManager",
        "devmanager.exe",
        "devmanager",
        "DevManager desktop client",
        &version,
        major,
        minor,
        patch,
        build,
    );
    stamp_windows_binary(
        "devmanager-host",
        "DevManager Host",
        "devmanager-host.exe",
        "devmanager-host",
        "DevManager durable host",
        &version,
        major,
        minor,
        patch,
        build,
    );
}

#[cfg(all(target_os = "windows", not(test)))]
#[allow(clippy::too_many_arguments)]
fn stamp_windows_binary(
    bin_name: &str,
    file_description: &str,
    original_filename: &str,
    internal_name: &str,
    comments: &str,
    version: &str,
    major: u16,
    minor: u16,
    patch: u16,
    build: u16,
) {
    use std::path::PathBuf;

    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let icon = manifest_dir.join("packaging/icons/devmanager.ico");
    let rc_path = out_dir.join(format!("{bin_name}-version.rc"));
    let icon_rc = icon.display().to_string().replace('\\', "\\\\");

    let rc = format!(
        r#"1 VERSIONINFO
FILEVERSION {major},{minor},{patch},{build}
PRODUCTVERSION {major},{minor},{patch},{build}
FILEOS 0x40004
FILETYPE 0x1
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904B0"
    BEGIN
      VALUE "CompanyName", "UserFirst"
      VALUE "FileDescription", "{file_description}"
      VALUE "FileVersion", "{version}"
      VALUE "InternalName", "{internal_name}"
      VALUE "LegalCopyright", "Copyright (c) UserFirst"
      VALUE "OriginalFilename", "{original_filename}"
      VALUE "ProductName", "DevManager"
      VALUE "ProductVersion", "{version}"
      VALUE "Comments", "{comments}"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x0409, 0x04B0
  END
END
IDI_ICON1 ICON "{icon_rc}"
"#
    );
    write_if_changed(&rc_path, rc.as_bytes());

    embed_resource::compile_for(&rc_path, [bin_name], embed_resource::NONE)
        .manifest_required()
        .unwrap_or_else(|error| {
            panic!("failed to embed Windows resources for {bin_name}: {error}")
        });
}

#[cfg(all(target_os = "windows", not(test)))]
fn windows_file_version_parts(version: &str) -> (u16, u16, u16, u16) {
    let mut parts = [0u16; 4];
    let normalized = version
        .split_once('-')
        .map(|(base, _)| base)
        .unwrap_or(version)
        .split_once('+')
        .map(|(base, _)| base)
        .unwrap_or(version);

    for (index, part) in normalized.split('.').take(4).enumerate() {
        parts[index] = part.parse::<u16>().unwrap_or(0);
    }
    (parts[0], parts[1], parts[2], parts[3])
}

const WEB_BUNDLE_RECOVERY: &str = "npm --prefix web ci && npm --prefix web run build";
const REQUIRED_ICONS: [&str; 4] = [
    "icons/devmanager-180.png",
    "icons/devmanager-192.png",
    "icons/devmanager-512.png",
    "icons/devmanager-maskable-512.png",
];
const FINGERPRINT_FILES: [&str; 6] = [
    "index.html",
    "package.json",
    "package-lock.json",
    "tsconfig.json",
    "tsconfig.node.json",
    "vite.config.ts",
];

fn validate_web_bundle() {
    let web_dir = std::path::Path::new("web");
    if !web_dir.exists() {
        println!("cargo:rustc-env=DEVMANAGER_WEB_BUILD_ID=unavailable");
        return;
    }

    for path in FINGERPRINT_FILES {
        println!("cargo:rerun-if-changed=web/{path}");
    }
    println!("cargo:rerun-if-changed=web/src");
    println!("cargo:rerun-if-changed=web/public");
    println!("cargo:rerun-if-changed=web/config");
    println!("cargo:rerun-if-changed=web/bundle");
    println!("cargo:rerun-if-changed=crates/connect-crypto/artifact-sources.txt");
    if let Ok(paths) = connect_crypto_source_paths(std::path::Path::new(".")) {
        for path in paths {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
    emit_bundle_rerun_directives(&web_dir.join("bundle"));

    if let Err(errors) = validate_web_bundle_at(web_dir) {
        panic!(
            "Embedded web bundle validation failed:\n- {}\nRecovery command: {}",
            errors.join("\n- "),
            WEB_BUNDLE_RECOVERY
        );
    }

    let fingerprint = std::fs::read_to_string(web_dir.join("bundle/source-fingerprint.txt"))
        .expect("validated web bundle fingerprint must remain readable");
    println!(
        "cargo:rustc-env=DEVMANAGER_WEB_BUILD_ID={}",
        fingerprint.trim()
    );
}

fn emit_bundle_rerun_directives(bundle: &std::path::Path) {
    let mut files = Vec::new();
    if collect_source_files(bundle, bundle, &mut files).is_ok() {
        for file in files {
            println!("cargo:rerun-if-changed=web/bundle/{file}");
        }
    }
}

fn validate_web_bundle_at(web_dir: &std::path::Path) -> Result<(), Vec<String>> {
    let bundle = web_dir.join("bundle");
    let mut errors = Vec::new();
    for path in [
        "index.html",
        "manifest.webmanifest",
        "sw.js",
        "source-fingerprint.txt",
    ]
    .into_iter()
    .chain(REQUIRED_ICONS)
    {
        if !bundle.join(path).is_file() {
            errors.push(format!("missing web/bundle/{path}"));
        }
    }

    let index = read_required_text(
        &bundle.join("index.html"),
        "web/bundle/index.html",
        &mut errors,
    );
    let manifest = read_required_text(
        &bundle.join("manifest.webmanifest"),
        "web/bundle/manifest.webmanifest",
        &mut errors,
    );
    let worker = read_required_text(&bundle.join("sw.js"), "web/bundle/sw.js", &mut errors);
    let fingerprint = read_required_text(
        &bundle.join("source-fingerprint.txt"),
        "web/bundle/source-fingerprint.txt",
        &mut errors,
    )
    .trim()
    .to_string();

    if !fingerprint_is_valid(&fingerprint) {
        errors.push(
            "web/bundle/source-fingerprint.txt must contain 16 lowercase hex characters"
                .to_string(),
        );
    }

    match compute_source_fingerprint(web_dir) {
        Ok(expected) if fingerprint != expected => errors.push(format!(
            "source fingerprint is stale: bundle has {fingerprint}, sources require {expected}"
        )),
        Err(error) => errors.push(error),
        _ => {}
    }

    validate_connect_crypto_artifacts(&bundle, &mut errors);

    let references = local_html_references(&index);
    if !references.iter().any(|path| path == "manifest.webmanifest") {
        errors.push("web/bundle/index.html does not reference manifest.webmanifest".to_string());
    }

    let mut hashed_assets = Vec::new();
    for reference in &references {
        if !safe_bundle_reference(reference) {
            errors.push(format!(
                "unsafe local reference in web/bundle/index.html: {reference}"
            ));
            continue;
        }
        if !bundle.join(reference).is_file() {
            errors.push(format!(
                "web/bundle/index.html references missing {reference}"
            ));
        }
        if reference.starts_with("assets/") {
            if !is_hashed_asset(reference) {
                errors.push(format!(
                    "web/bundle/index.html references unhashed asset {reference}"
                ));
            }
            hashed_assets.push(reference.clone());
        }
    }
    if hashed_assets.is_empty() {
        errors.push("web/bundle/index.html does not reference any hashed assets".to_string());
    }
    let referenced_assets = validate_asset_graph(&bundle, &hashed_assets, &mut errors);

    for needle in [
        "\"id\":\"/\"",
        "\"scope\":\"/\"",
        "\"start_url\":\"/tasks?source=pwa\"",
        "\"display\":\"standalone\"",
    ] {
        if !manifest.contains(needle) {
            errors.push(format!(
                "web/bundle/manifest.webmanifest is missing {needle}"
            ));
        }
    }
    if manifest.contains("\"orientation\"") {
        errors.push("web/bundle/manifest.webmanifest must not lock orientation".to_string());
    }
    for icon in REQUIRED_ICONS {
        if icon != "icons/devmanager-180.png" && !manifest.contains(icon) {
            errors.push(format!(
                "web/bundle/manifest.webmanifest does not reference {icon}"
            ));
        }
    }

    for reference in referenced_assets
        .iter()
        .map(String::as_str)
        .chain(std::iter::once("index.html"))
        .chain(std::iter::once("manifest.webmanifest"))
        .chain(REQUIRED_ICONS)
    {
        if !worker.contains(reference) {
            errors.push(format!("web/bundle/sw.js does not precache {reference}"));
        }
    }
    if worker.contains("source-fingerprint.txt") {
        errors.push("web/bundle/sw.js must not precache source-fingerprint.txt".to_string());
    }
    for marker in ["\"/api\"", "\"/api/\"", "\"/pair\""] {
        if !worker.contains(marker) {
            errors.push(format!(
                "web/bundle/sw.js is missing NetworkOnly policy marker {marker}"
            ));
        }
    }

    let fingerprint_meta = format!("name=\"devmanager-web-build\" content=\"{fingerprint}\"");
    if !index.contains(&fingerprint_meta) {
        errors.push(
            "web/bundle/index.html fingerprint does not match source-fingerprint.txt".to_string(),
        );
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

fn read_required_text(path: &std::path::Path, label: &str, errors: &mut Vec<String>) -> String {
    match std::fs::read_to_string(path) {
        Ok(contents) => contents,
        Err(error) => {
            errors.push(format!("cannot read {label}: {error}"));
            String::new()
        }
    }
}

fn fingerprint_is_valid(fingerprint: &str) -> bool {
    fingerprint.len() == 16
        && fingerprint
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn compute_source_fingerprint(web_dir: &std::path::Path) -> Result<String, String> {
    let mut files = Vec::new();
    for path in FINGERPRINT_FILES {
        let source = web_dir.join(path);
        if !source.is_file() {
            return Err(format!("missing web source file web/{path}"));
        }
        files.push(path.to_string());
    }
    for root in ["src", "public", "config"] {
        collect_source_files(web_dir, &web_dir.join(root), &mut files)?;
    }
    files.sort();
    files.dedup();

    let mut hash = 0xcbf29ce484222325_u64;
    for relative in files {
        update_fingerprint(&mut hash, relative.as_bytes());
        update_fingerprint(&mut hash, &[0]);
        let contents = std::fs::read(web_dir.join(&relative))
            .map_err(|error| format!("cannot read web/{relative}: {error}"))?;
        update_fingerprint(&mut hash, &contents);
        update_fingerprint(&mut hash, &[0]);
    }
    Ok(format!("{hash:016x}"))
}

fn collect_source_files(
    web_dir: &std::path::Path,
    directory: &std::path::Path,
    files: &mut Vec<String>,
) -> Result<(), String> {
    let entries = std::fs::read_dir(directory)
        .map_err(|error| format!("cannot scan {}: {error}", directory.display()))?;
    for entry in entries {
        let entry =
            entry.map_err(|error| format!("cannot scan {}: {error}", directory.display()))?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|error| format!("cannot inspect {}: {error}", path.display()))?;
        if file_type.is_dir() {
            collect_source_files(web_dir, &path, files)?;
        } else if file_type.is_file() {
            let relative = path
                .strip_prefix(web_dir)
                .map_err(|error| format!("cannot relativize {}: {error}", path.display()))?
                .to_string_lossy()
                .replace('\\', "/");
            files.push(relative);
        }
    }
    Ok(())
}

fn update_fingerprint(hash: &mut u64, bytes: &[u8]) {
    let mut index = 0;
    while index < bytes.len() {
        let byte = if bytes[index] == b'\r' && bytes.get(index + 1) == Some(&b'\n') {
            index += 2;
            b'\n'
        } else {
            let byte = bytes[index];
            index += 1;
            byte
        };
        *hash ^= u64::from(byte);
        *hash = (*hash).wrapping_mul(0x100000001b3);
    }
}

fn local_html_references(html: &str) -> Vec<String> {
    let mut references = Vec::new();
    for (marker, quote) in [
        ("src=\"", '"'),
        ("href=\"", '"'),
        ("src='", '\''),
        ("href='", '\''),
    ] {
        let mut remaining = html;
        while let Some(start) = remaining.find(marker) {
            let value = &remaining[start + marker.len()..];
            let Some(end) = value.find(quote) else {
                break;
            };
            if let Some(reference) = normalize_local_reference(&value[..end]) {
                references.push(reference);
            }
            remaining = &value[end + 1..];
        }
    }
    references.sort();
    references.dedup();
    references
}

fn normalize_local_reference(reference: &str) -> Option<String> {
    if reference.is_empty()
        || reference.starts_with('#')
        || reference.starts_with("//")
        || reference.contains("://")
        || reference.starts_with("data:")
    {
        return None;
    }
    let without_fragment = reference.split(['?', '#']).next().unwrap_or("");
    let normalized = without_fragment.trim_start_matches('/');
    (!normalized.is_empty()).then(|| normalized.to_string())
}

fn safe_bundle_reference(reference: &str) -> bool {
    !reference.contains("..") && !reference.contains('\\') && !reference.contains(':')
}

fn validate_asset_graph(
    bundle: &std::path::Path,
    roots: &[String],
    errors: &mut Vec<String>,
) -> std::collections::BTreeSet<String> {
    let mut referenced = std::collections::BTreeSet::new();
    let mut pending = std::collections::VecDeque::from(roots.to_vec());

    while let Some(asset) = pending.pop_front() {
        if !referenced.insert(asset.clone()) {
            continue;
        }
        // The reviewed wasm-bindgen module has a fixed runtime import path.
        // Its exact files and manifest are validated separately; do not turn
        // this exception into a general allowance for unhashed assets.
        let connect_artifact = asset
            .strip_prefix("assets/wasm/")
            .is_some_and(|name| CONNECT_CRYPTO_ARTIFACT_FILES.contains(&name));
        if !safe_bundle_reference(&asset) || !(is_hashed_asset(&asset) || connect_artifact) {
            errors.push(format!(
                "generated asset reference is not a safe hashed path: {asset}"
            ));
            continue;
        }

        let path = bundle.join(&asset);
        if !path.is_file() {
            errors.push(format!("generated asset graph references missing {asset}"));
            continue;
        }
        // wasm-bindgen's JS includes type annotations and an import-object key
        // ending in _bg.js; those strings are not fetches. Its reviewed fixed
        // artifact set is a leaf validated by validate_connect_crypto_artifacts,
        // not a Vite chunk to scan with the relative-import heuristic.
        if connect_artifact {
            continue;
        }
        if !asset.ends_with(".js") && !asset.ends_with(".css") {
            continue;
        }
        let contents = match std::fs::read_to_string(&path) {
            Ok(contents) => contents,
            Err(error) => {
                errors.push(format!("cannot read generated asset {asset}: {error}"));
                continue;
            }
        };
        pending.extend(relative_asset_references(&asset, &contents));
    }

    let mut generated_assets = Vec::new();
    if let Err(error) = collect_source_files(bundle, &bundle.join("assets"), &mut generated_assets)
    {
        errors.push(error);
    }
    for asset in generated_assets {
        // Connect's Rust/WASM leaf is loaded by an explicit runtime path, not
        // by Vite's static graph.  Its manifest and exact file allowlist are
        // checked separately above, so it is intentionally not required to
        // be reachable from index.html or the service-worker shell graph.
        if asset.starts_with("assets/wasm/") {
            continue;
        }
        if !referenced.contains(&asset) {
            errors.push(format!(
                "web/bundle contains unreferenced generated asset {asset}"
            ));
        }
    }

    referenced
}

const CONNECT_CRYPTO_ARTIFACT_FILES: [&str; 5] = [
    "connect_crypto.js",
    "connect_crypto_bg.wasm",
    "connect_crypto.d.ts",
    "connect_crypto_bg.wasm.d.ts",
    "connect_crypto.manifest.json",
];

fn validate_connect_crypto_artifacts(bundle: &std::path::Path, errors: &mut Vec<String>) {
    let directory = bundle.join("assets/wasm");
    if !directory.is_dir() {
        // A clean checkout deliberately has no browser crypto artifact.  The
        // TypeScript loader reports a typed HOLD until the explicit pinned
        // build script produces it.
        return;
    }

    let manifest = directory.join("connect_crypto.manifest.json");
    if !manifest.is_file() {
        errors.push(
            "web/bundle/assets/wasm is present but connect_crypto.manifest.json is missing"
                .to_string(),
        );
    } else if let Ok(contents) = std::fs::read_to_string(&manifest) {
        let compact: String = contents
            .chars()
            .filter(|character| !character.is_ascii_whitespace())
            .collect();
        for required in [
            "\"schemaVersion\":1",
            "\"artifact\":\"connect-crypto\"",
            "\"protocolMajor\":1",
            "\"target\":\"wasm32-unknown-unknown\"",
            "\"wasmBindgenVersion\":\"0.2.114\"",
            "\"modulePath\":\"./wasm/connect_crypto.js\"",
        ] {
            if !compact.contains(required) {
                errors.push(format!(
                    "web/bundle/assets/wasm/connect_crypto.manifest.json is missing {required}"
                ));
            }
        }
        let repository = bundle
            .parent()
            .and_then(std::path::Path::parent)
            .unwrap_or_else(|| std::path::Path::new("."));
        match connect_crypto_source_fingerprint(repository) {
            Ok(expected) => {
                let required = format!("\"sourceFingerprint\":\"{expected}\"");
                if !compact.contains(&required) {
                    errors.push(format!(
                        "web/bundle Connect crypto artifact is stale: sources require {expected}"
                    ));
                }
            }
            Err(error) => errors.push(error),
        }
    } else {
        errors
            .push("web/bundle/assets/wasm/connect_crypto.manifest.json is unreadable".to_string());
    }

    let entries = match std::fs::read_dir(&directory) {
        Ok(entries) => entries,
        Err(error) => {
            errors.push(format!("cannot scan web/bundle/assets/wasm: {error}"));
            return;
        }
    };
    for entry in entries {
        let Ok(entry) = entry else {
            errors.push("cannot inspect an entry in web/bundle/assets/wasm".to_string());
            continue;
        };
        let path = entry.path();
        if !path.is_file() {
            errors.push(format!(
                "web/bundle/assets/wasm contains a non-file entry: {}",
                path.display()
            ));
            continue;
        }
        let Some(name) = path.file_name().and_then(|value| value.to_str()) else {
            errors.push(format!(
                "web/bundle/assets/wasm contains an invalid file name: {}",
                path.display()
            ));
            continue;
        };
        if !CONNECT_CRYPTO_ARTIFACT_FILES.contains(&name) {
            errors.push(format!(
                "web/bundle/assets/wasm contains unexpected file: {name}"
            ));
        }
    }

    for required in ["connect_crypto.js", "connect_crypto_bg.wasm"] {
        if !directory.join(required).is_file() {
            errors.push(format!(
                "web/bundle/assets/wasm is missing required artifact {required}"
            ));
        }
    }
}

fn connect_crypto_source_paths(
    repository: &std::path::Path,
) -> Result<Vec<std::path::PathBuf>, String> {
    let manifest = repository.join("crates/connect-crypto/artifact-sources.txt");
    let contents = std::fs::read_to_string(&manifest)
        .map_err(|error| format!("cannot read {}: {error}", manifest.display()))?;
    let mut files = Vec::new();
    for source in contents.lines().map(str::trim) {
        if source.is_empty() || source.starts_with('#') {
            continue;
        }
        let path = repository.join(source);
        if path.is_dir() {
            collect_connect_crypto_source_files(&path, &mut files)?;
        } else if path.is_file() {
            files.push(path);
        } else {
            return Err(format!("Connect crypto source path is missing: {source}"));
        }
    }
    files.sort();
    Ok(files)
}

fn collect_connect_crypto_source_files(
    directory: &std::path::Path,
    files: &mut Vec<std::path::PathBuf>,
) -> Result<(), String> {
    let entries = std::fs::read_dir(directory)
        .map_err(|error| format!("cannot scan {}: {error}", directory.display()))?;
    for entry in entries {
        let entry =
            entry.map_err(|error| format!("cannot inspect {}: {error}", directory.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_connect_crypto_source_files(&path, files)?;
        } else if path.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

fn connect_crypto_source_fingerprint(repository: &std::path::Path) -> Result<String, String> {
    let mut hash = 0xcbf29ce484222325_u64;
    for path in connect_crypto_source_paths(repository)? {
        let relative = path
            .strip_prefix(repository)
            .map_err(|_| {
                format!(
                    "Connect crypto source escaped repository: {}",
                    path.display()
                )
            })?
            .to_string_lossy()
            .replace('\\', "/");
        update_connect_crypto_fingerprint(&mut hash, relative.as_bytes());
        update_connect_crypto_fingerprint(&mut hash, &[0]);
        let contents = std::fs::read(&path)
            .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
        update_connect_crypto_fingerprint(&mut hash, &contents);
        update_connect_crypto_fingerprint(&mut hash, &[0]);
    }
    Ok(format!("{hash:016x}"))
}

fn update_connect_crypto_fingerprint(hash: &mut u64, bytes: &[u8]) {
    let mut index = 0;
    while index < bytes.len() {
        let byte = if bytes[index] == b'\r' && bytes.get(index + 1) == Some(&b'\n') {
            index += 1;
            b'\n'
        } else {
            bytes[index]
        };
        *hash ^= u64::from(byte);
        *hash = hash.wrapping_mul(0x100000001b3);
        index += 1;
    }
}

fn relative_asset_references(current: &str, contents: &str) -> Vec<String> {
    let parent = std::path::Path::new(current)
        .parent()
        .unwrap_or_else(|| std::path::Path::new(""));
    let mut references = Vec::new();

    for (marker, quote) in [("\"./", '"'), ("'./", '\'')] {
        let mut remaining = contents;
        while let Some(start) = remaining.find(marker) {
            let value = &remaining[start + marker.len()..];
            let Some(end) = value.find(quote) else {
                break;
            };
            let target = value[..end].split(['?', '#']).next().unwrap_or("");
            if !target.is_empty() {
                let reference = parent.join(target).to_string_lossy().replace('\\', "/");
                if reference.starts_with("assets/") {
                    references.push(reference);
                }
            }
            remaining = &value[end + 1..];
        }
    }

    // Vite's preload dependency map records split-chunk companion assets as
    // bundle-root paths (for example "assets/Terminal-<hash>.css") while the
    // dynamic import itself remains "./Terminal-<hash>.js". Follow both forms
    // so legitimate lazy CSS is part of the same validated asset graph.
    for (marker, quote) in [("\"assets/", '"'), ("'assets/", '\'')] {
        let mut remaining = contents;
        while let Some(start) = remaining.find(marker) {
            let value = &remaining[start + marker.len()..];
            let Some(end) = value.find(quote) else {
                break;
            };
            let target = value[..end].split(['?', '#']).next().unwrap_or("");
            if !target.is_empty() {
                references.push(format!("assets/{target}"));
            }
            remaining = &value[end + 1..];
        }
    }

    references.sort();
    references.dedup();
    references
}

fn is_hashed_asset(path: &str) -> bool {
    if !path.starts_with("assets/") {
        return false;
    }
    let filename = path.rsplit('/').next().unwrap_or(path);
    let stem = filename.rsplit_once('.').map_or(filename, |(stem, _)| stem);
    let bytes = stem.as_bytes();
    bytes.len() > 9
        && bytes[bytes.len() - 9] == b'-'
        && bytes[bytes.len() - 8..]
            .iter()
            .all(|byte| byte.is_ascii_alphanumeric() || *byte == b'_' || *byte == b'-')
}

#[cfg(test)]
mod bundle_graph_tests {
    use super::*;

    #[test]
    fn fixed_connect_import_is_validated_without_allowing_arbitrary_unhashed_assets() {
        let bundle =
            std::env::temp_dir().join(format!("devmanager-bundle-graph-{}", std::process::id()));
        std::fs::create_dir(&bundle).expect("unique test directory");
        struct Cleanup(std::path::PathBuf);
        impl Drop for Cleanup {
            fn drop(&mut self) {
                let _ = std::fs::remove_dir_all(&self.0);
            }
        }
        let _cleanup = Cleanup(bundle.clone());
        std::fs::create_dir_all(bundle.join("assets/wasm")).unwrap();
        std::fs::write(
            bundle.join("assets/index-12345678.js"),
            "import('./wasm/connect_crypto.js')",
        )
        .unwrap();
        std::fs::write(
            bundle.join("assets/wasm/connect_crypto.js"),
            "new URL('./connect_crypto_bg.wasm', import.meta.url)",
        )
        .unwrap();
        std::fs::write(bundle.join("assets/wasm/connect_crypto_bg.wasm"), b"\0asm").unwrap();
        let roots = vec!["assets/index-12345678.js".to_owned()];
        let mut errors = Vec::new();
        let reached = validate_asset_graph(&bundle, &roots, &mut errors);
        assert!(errors.is_empty(), "{errors:?}");
        assert!(reached.contains("assets/wasm/connect_crypto.js"));

        // Referenced allowlisted files still must exist.
        std::fs::remove_file(bundle.join("assets/wasm/connect_crypto.js")).unwrap();
        errors.clear();
        validate_asset_graph(&bundle, &roots, &mut errors);
        assert!(errors
            .iter()
            .any(|error| error.contains("references missing")));

        for invalid in [
            "assets/plain.js",
            "assets/wasm/other.js",
            "assets/wasm/../connect_crypto.js",
        ] {
            errors.clear();
            validate_asset_graph(&bundle, &[invalid.to_owned()], &mut errors);
            assert!(
                errors
                    .iter()
                    .any(|error| error.contains("not a safe hashed path")),
                "{invalid}: {errors:?}"
            );
        }
    }
}
