import type { WebAiKind } from "../../api/types";
import type {
  SlashCommand,
  SlashCommandCategory,
  SlashCommandInteraction,
  SlashCommandSuggestion,
} from "./types";

export const BUILTIN_CATALOG_REVIEWED_AT = "2026-07-15";

type Seed = readonly [
  name: `/${string}`,
  description: string,
  options?: {
    category?: SlashCommandCategory;
    argumentHint?: string;
    suggestions?: readonly SlashCommandSuggestion[];
    aliases?: readonly string[];
    interaction?: SlashCommandInteraction;
  },
];

function catalog(provider: WebAiKind, seeds: readonly Seed[]): SlashCommand[] {
  return seeds.map(([name, description, options]) => ({
    name,
    description,
    provider,
    source: "builtin",
    category: options?.category ?? "workflow",
    argumentHint: options?.argumentHint ?? null,
    suggestions: [...(options?.suggestions ?? [])],
    aliases: [...(options?.aliases ?? [])],
    interaction: options?.interaction ?? "inline",
  }));
}

const CLAUDE_SEEDS: readonly Seed[] = [
  ["/add-dir", "Add a working directory for file access.", { category: "configuration", argumentHint: "path" }],
  ["/advisor", "Consult a second model for guidance.", { category: "model", argumentHint: "opus | sonnet | fable | off", suggestions: [{ label: "Opus", value: "opus" }, { label: "Sonnet", value: "sonnet" }, { label: "Fable", value: "fable" }, { label: "Off", value: "off" }], interaction: "providerMenu" }],
  ["/agents", "Create or manage subagent configurations.", { category: "tools" }],
  ["/autofix-pr", "Watch a pull request and fix CI or review feedback.", { argumentHint: "optional instructions" }],
  ["/background", "Detach this session as a background agent.", { aliases: ["bg"], argumentHint: "optional prompt" }],
  ["/batch", "Orchestrate a large change across parallel work units.", { argumentHint: "instruction" }],
  ["/branch", "Branch this conversation from the current point.", { category: "session", argumentHint: "optional name" }],
  ["/btw", "Ask a side question outside the main conversation.", { category: "session", argumentHint: "question" }],
  ["/cd", "Move the session to another working directory.", { category: "configuration", argumentHint: "path" }],
  ["/chrome", "Configure Claude in Chrome.", { category: "configuration", interaction: "providerMenu" }],
  ["/claude-api", "Load Claude API guidance or migration help.", { category: "tools", argumentHint: "migrate | managed-agents-onboard" }],
  ["/clear", "Start a new conversation with empty context.", { category: "session", aliases: ["reset", "new"], argumentHint: "optional previous-session name" }],
  ["/code-review", "Review the current diff for correctness and cleanup.", { argumentHint: "effort, flags, or target" }],
  ["/color", "Set the prompt bar color.", { category: "configuration", argumentHint: "color | default" }],
  ["/compact", "Summarize the conversation to free context space.", { category: "session", argumentHint: "optional focus instructions" }],
  ["/config", "Open or update Claude Code settings.", { category: "configuration", aliases: ["settings"], argumentHint: "key=value", interaction: "providerMenu" }],
  ["/context", "Visualize what is using the conversation context.", { category: "diagnostics", argumentHint: "all" }],
  ["/copy", "Copy a recent assistant response or code block.", { category: "tools", argumentHint: "optional response number", interaction: "providerMenu" }],
  ["/cost", "Show session and plan usage.", { category: "diagnostics", aliases: ["usage", "stats"] }],
  ["/dataviz", "Apply chart and dashboard design guidance.", { category: "tools", argumentHint: "optional request" }],
  ["/debug", "Enable debug logging and investigate a problem.", { category: "diagnostics", argumentHint: "optional description" }],
  ["/deep-research", "Research a question with cross-checked web sources.", { category: "tools", argumentHint: "question" }],
  ["/design-login", "Authorize Claude Design access.", { category: "account" }],
  ["/design-sync", "Upload the repository design system to Claude Design.", { category: "tools", argumentHint: "optional hint" }],
  ["/desktop", "Continue the session in Claude Code Desktop.", { category: "session", aliases: ["app"] }],
  ["/diff", "Open the interactive working-tree diff viewer.", { category: "tools", interaction: "providerMenu" }],
  ["/doctor", "Diagnose and optionally repair Claude Code setup.", { category: "diagnostics", aliases: ["checkup"], interaction: "providerMenu" }],
  ["/effort", "Set the model reasoning effort level.", { category: "model", argumentHint: "low | medium | high | xhigh | max | auto", suggestions: [{ label: "Auto", value: "auto" }, { label: "Low", value: "low" }, { label: "Medium", value: "medium" }, { label: "High", value: "high" }, { label: "Max", value: "max" }], interaction: "providerMenu" }],
  ["/exit", "Exit or detach from the Claude CLI.", { category: "session", aliases: ["quit"] }],
  ["/export", "Export the current conversation.", { category: "tools", argumentHint: "optional filename", interaction: "providerMenu" }],
  ["/fast", "Toggle fast mode.", { category: "model", argumentHint: "on | off", suggestions: [{ label: "On", value: "on" }, { label: "Off", value: "off" }] }],
  ["/feedback", "Send feedback or a bug report to Anthropic.", { category: "account", aliases: ["bug", "share"], argumentHint: "optional report", interaction: "providerMenu" }],
  ["/fewer-permission-prompts", "Build a safe allowlist from common read-only tools.", { category: "configuration" }],
  ["/focus", "Toggle the focused conversation view.", { category: "configuration" }],
  ["/fork", "Send a side directive to a forked subagent.", { category: "session", argumentHint: "directive" }],
  ["/goal", "Set, inspect, or clear a persistent goal.", { category: "session", argumentHint: "condition | clear" }],
  ["/heapdump", "Write a JavaScript heap snapshot for diagnostics.", { category: "diagnostics" }],
  ["/help", "Show help and commands.", { category: "diagnostics", interaction: "providerMenu" }],
  ["/hooks", "View tool-event hook configuration.", { category: "configuration", interaction: "providerMenu" }],
  ["/ide", "Manage IDE integrations and status.", { category: "configuration", interaction: "providerMenu" }],
  ["/init", "Initialize the project with a CLAUDE.md guide.", { category: "configuration" }],
  ["/insights", "Analyze recent Claude Code usage and friction.", { category: "diagnostics" }],
  ["/install-github-app", "Install and configure the Claude GitHub App.", { category: "account", interaction: "providerMenu" }],
  ["/install-slack-app", "Install the Claude Slack app.", { category: "account" }],
  ["/keybindings", "Open the keyboard shortcut configuration.", { category: "configuration" }],
  ["/login", "Sign in to an Anthropic account.", { category: "account", interaction: "providerMenu" }],
  ["/logout", "Sign out of the Anthropic account.", { category: "account", interaction: "providerMenu" }],
  ["/loop", "Run a prompt repeatedly while the session remains open.", { aliases: ["proactive"], argumentHint: "interval and prompt" }],
  ["/mcp", "Manage MCP connections and authentication.", { category: "tools", argumentHint: "reconnect | enable | disable", interaction: "providerMenu" }],
  ["/memory", "Manage CLAUDE.md and auto-memory.", { category: "configuration", interaction: "providerMenu" }],
  ["/mobile", "Show a QR code for the Claude mobile app.", { category: "account", aliases: ["ios", "android"] }],
  ["/model", "Switch the Claude model used by this session.", { category: "model", argumentHint: "model", interaction: "providerMenu" }],
  ["/passes", "Share an eligible Claude Code trial pass.", { category: "account" }],
  ["/permissions", "Manage allow, ask, and deny tool rules.", { category: "configuration", aliases: ["allowed-tools"], interaction: "providerMenu" }],
  ["/plan", "Enter plan mode with an optional task description.", { argumentHint: "optional description" }],
  ["/plugin", "Manage Claude Code plugins.", { category: "tools", argumentHint: "subcommand", interaction: "providerMenu" }],
  ["/powerup", "Explore Claude Code features through lessons.", { category: "diagnostics", interaction: "providerMenu" }],
  ["/privacy-settings", "View and update privacy settings.", { category: "account", interaction: "providerMenu" }],
  ["/radio", "Open Claude FM radio.", { category: "tools" }],
  ["/recap", "Generate a one-line session recap.", { category: "session" }],
  ["/release-notes", "Browse Claude Code release notes.", { category: "diagnostics", interaction: "providerMenu" }],
  ["/reload-plugins", "Reload active plugins without restarting.", { category: "tools", argumentHint: "--force" }],
  ["/reload-skills", "Rescan skill and custom command directories.", { category: "tools" }],
  ["/remote-control", "Expose this session through Claude Remote Control.", { category: "session", aliases: ["rc"] }],
  ["/remote-env", "Choose the default environment for cloud agents.", { category: "configuration", interaction: "providerMenu" }],
  ["/rename", "Rename the current session.", { category: "session", argumentHint: "optional name" }],
  ["/resume", "Resume a saved conversation.", { category: "session", aliases: ["continue"], argumentHint: "optional session", interaction: "providerMenu" }],
  ["/review", "Review a GitHub pull request.", { argumentHint: "optional PR", interaction: "providerMenu" }],
  ["/rewind", "Rewind conversation or code to a checkpoint.", { category: "session", aliases: ["checkpoint", "undo"], interaction: "providerMenu" }],
  ["/run", "Launch and verify the project application.", { category: "tools" }],
  ["/run-skill-generator", "Teach run and verify how to drive this project.", { category: "tools" }],
  ["/sandbox", "Toggle sandbox mode.", { category: "configuration", interaction: "providerMenu" }],
  ["/schedule", "Create and manage cloud routines.", { aliases: ["routines"], argumentHint: "optional description", interaction: "providerMenu" }],
  ["/scroll-speed", "Adjust fullscreen mouse-wheel scroll speed.", { category: "configuration", interaction: "providerMenu" }],
  ["/security-review", "Analyze pending changes for vulnerabilities.", { category: "tools" }],
  ["/setup-bedrock", "Configure Amazon Bedrock authentication.", { category: "configuration", interaction: "providerMenu" }],
  ["/setup-vertex", "Configure Google Cloud model authentication.", { category: "configuration", interaction: "providerMenu" }],
  ["/simplify", "Review changed code for focused cleanup.", { argumentHint: "optional target" }],
  ["/skills", "Browse and configure available skills.", { category: "tools", interaction: "providerMenu" }],
  ["/stats", "Open detailed usage statistics.", { category: "diagnostics", aliases: ["usage", "cost"], interaction: "providerMenu" }],
  ["/status", "Show version, model, account, and connectivity.", { category: "diagnostics", interaction: "providerMenu" }],
  ["/statusline", "Configure the terminal status line.", { category: "configuration", argumentHint: "optional description", interaction: "providerMenu" }],
  ["/stickers", "Order Claude Code stickers.", { category: "account" }],
  ["/stop", "Stop the attached background session.", { category: "session" }],
  ["/tasks", "View and manage background work.", { category: "tools", aliases: ["bashes"], interaction: "providerMenu" }],
  ["/team-onboarding", "Generate a team onboarding guide from usage.", { category: "tools" }],
  ["/teleport", "Pull a Claude web session into this terminal.", { category: "session", aliases: ["tp"], interaction: "providerMenu" }],
  ["/terminal-setup", "Configure terminal shortcuts.", { category: "configuration", interaction: "providerMenu" }],
  ["/theme", "Choose a built-in or custom terminal theme.", { category: "configuration", interaction: "providerMenu" }],
  ["/tui", "Choose the default or fullscreen terminal renderer.", { category: "configuration", argumentHint: "default | fullscreen", suggestions: [{ label: "Default", value: "default" }, { label: "Fullscreen", value: "fullscreen" }] }],
  ["/ultraplan", "Draft and review a deep plan in the browser.", { argumentHint: "prompt" }],
  ["/ultrareview", "Run a deep cloud code review.", { argumentHint: "optional PR" }],
  ["/upgrade", "Open the subscription upgrade page.", { category: "account" }],
  ["/usage", "Show session cost and plan usage limits.", { category: "diagnostics", aliases: ["cost", "stats"], interaction: "providerMenu" }],
  ["/usage-credits", "Configure usage credits and spending limits.", { category: "account", interaction: "providerMenu" }],
  ["/verify", "Build, run, and observe a code change.", { category: "tools" }],
  ["/voice", "Configure Claude voice dictation.", { category: "configuration", argumentHint: "hold | tap | off", suggestions: [{ label: "Hold", value: "hold" }, { label: "Tap", value: "tap" }, { label: "Off", value: "off" }] }],
  ["/web-setup", "Connect GitHub credentials to Claude Code on the web.", { category: "account" }],
  ["/workflows", "View and manage workflow progress.", { category: "tools", interaction: "providerMenu" }],
];

const CODEX_SEEDS: readonly Seed[] = [
  ["/permissions", "Set what Codex may do without asking.", { category: "configuration", interaction: "providerMenu" }],
  ["/ide", "Include files and selections from the IDE.", { category: "configuration", interaction: "providerMenu" }],
  ["/keymap", "Inspect and remap terminal shortcuts.", { category: "configuration", interaction: "providerMenu" }],
  ["/vim", "Toggle Vim editing mode.", { category: "configuration" }],
  ["/setup-default-sandbox", "Set up the elevated Windows sandbox.", { category: "configuration", interaction: "providerMenu" }],
  ["/sandbox-add-read-dir", "Grant sandbox read access to another directory.", { category: "configuration", argumentHint: "path" }],
  ["/agent", "Inspect or switch agent threads.", { category: "tools", aliases: ["subagents"], interaction: "providerMenu" }],
  ["/apps", "Browse apps and insert one into the prompt.", { category: "tools", interaction: "providerMenu" }],
  ["/plugins", "Browse and manage Codex plugins.", { category: "tools", interaction: "providerMenu" }],
  ["/hooks", "View and manage lifecycle hooks.", { category: "configuration", interaction: "providerMenu" }],
  ["/clear", "Clear the terminal and start a new task.", { category: "session" }],
  ["/rename", "Rename the current task.", { category: "session", argumentHint: "name" }],
  ["/archive", "Archive the session and exit Codex.", { category: "session" }],
  ["/delete", "Permanently delete this session and descendants.", { category: "session", interaction: "providerMenu" }],
  ["/compact", "Summarize the conversation to free context.", { category: "session" }],
  ["/copy", "Copy the latest completed Codex response.", { category: "tools" }],
  ["/diff", "Show the complete Git working-tree diff.", { category: "tools" }],
  ["/exit", "Exit the Codex CLI.", { category: "session", aliases: ["quit"] }],
  ["/experimental", "Toggle experimental Codex features.", { category: "configuration", interaction: "providerMenu" }],
  ["/approve", "Retry a command denied by auto review.", { category: "tools" }],
  ["/memories", "Configure memory injection and generation.", { category: "configuration", interaction: "providerMenu" }],
  ["/skills", "Browse and use installed skills.", { category: "tools", interaction: "providerMenu" }],
  ["/import", "Import supported Claude Code configuration.", { category: "configuration", interaction: "providerMenu" }],
  ["/feedback", "Send feedback and diagnostics to OpenAI.", { category: "account", interaction: "providerMenu" }],
  ["/init", "Generate an AGENTS.md scaffold.", { category: "configuration" }],
  ["/logout", "Sign out of Codex.", { category: "account", interaction: "providerMenu" }],
  ["/mcp", "List configured MCP servers and tools.", { category: "tools", interaction: "providerMenu" }],
  ["/mention", "Attach a file or folder to the prompt.", { category: "tools", interaction: "providerMenu" }],
  ["/model", "Choose the model and reasoning effort.", { category: "model", interaction: "providerMenu" }],
  ["/fast", "Toggle the model's Fast service tier.", { category: "model" }],
  ["/plan", "Switch to plan mode with an optional prompt.", { argumentHint: "optional prompt" }],
  ["/goal", "Set, inspect, pause, or clear a task goal.", { category: "session", interaction: "providerMenu" }],
  ["/personality", "Choose a Codex communication style.", { category: "model", interaction: "providerMenu" }],
  ["/ps", "Inspect background terminals and recent output.", { category: "tools", interaction: "providerMenu" }],
  ["/stop", "Stop background terminals for this session.", { category: "tools", interaction: "providerMenu" }],
  ["/fork", "Fork this task into a new task.", { category: "session" }],
  ["/app", "Continue this session in the desktop app.", { category: "session" }],
  ["/side", "Start an ephemeral side conversation.", { category: "session", aliases: ["btw"], interaction: "providerMenu" }],
  ["/raw", "Toggle raw scrollback mode.", { category: "configuration" }],
  ["/resume", "Resume a saved conversation.", { category: "session", interaction: "providerMenu" }],
  ["/new", "Start a new conversation in this CLI session.", { category: "session" }],
  ["/quit", "Exit the Codex CLI.", { category: "session", aliases: ["exit"] }],
  ["/review", "Review the current working tree.", { category: "workflow", interaction: "providerMenu" }],
  ["/status", "Show model, permissions, usage, and context.", { category: "diagnostics", interaction: "providerMenu" }],
  ["/usage", "Show token usage and rate-limit timing.", { category: "diagnostics", interaction: "providerMenu" }],
  ["/debug-config", "Print layered configuration diagnostics.", { category: "diagnostics" }],
  ["/statusline", "Choose and order terminal footer fields.", { category: "configuration", interaction: "providerMenu" }],
  ["/title", "Choose terminal title fields.", { category: "configuration", interaction: "providerMenu" }],
  ["/theme", "Choose a syntax-highlighting theme.", { category: "configuration", interaction: "providerMenu" }],
  ["/pets", "Choose or hide a terminal pet.", { category: "configuration", aliases: ["pet"], interaction: "providerMenu" }],
];

export const CLAUDE_BUILTIN_COMMANDS = catalog("claude", CLAUDE_SEEDS);
export const CODEX_BUILTIN_COMMANDS = catalog("codex", CODEX_SEEDS);
