//! Reviewed Rust-owned provider slash-command seeds.
//!
//! This module is the sole source of truth. `build.rs` mirrors it into
//! TypeScript. Do not scrape TypeScript and do not silently return empty.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CatalogSeed {
    pub command: &'static str,
    pub description: &'static str,
    pub aliases: &'static [&'static str],
    pub opens_provider_menu: bool,
    pub category: Option<&'static str>,
    pub argument_hint: Option<&'static str>,
}

pub const CATALOG_REVIEWED_AT: &str = "2026-07-15";

pub const CLAUDE_SEEDS: &[CatalogSeed] = &[
    CatalogSeed {
        command: "/add-dir",
        description: "Add a working directory for file access.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: Some("path"),
    },
    CatalogSeed {
        command: "/advisor",
        description: "Consult a second model for guidance.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("model"),
        argument_hint: Some("opus | sonnet | fable | off"),
    },
    CatalogSeed {
        command: "/agents",
        description: "Create or manage subagent configurations.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/autofix-pr",
        description: "Watch a pull request and fix CI or review feedback.",
        aliases: &[],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("optional instructions"),
    },
    CatalogSeed {
        command: "/background",
        description: "Detach this session as a background agent.",
        aliases: &["bg"],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("optional prompt"),
    },
    CatalogSeed {
        command: "/batch",
        description: "Orchestrate a large change across parallel work units.",
        aliases: &[],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("instruction"),
    },
    CatalogSeed {
        command: "/branch",
        description: "Branch this conversation from the current point.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: Some("optional name"),
    },
    CatalogSeed {
        command: "/btw",
        description: "Ask a side question outside the main conversation.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: Some("question"),
    },
    CatalogSeed {
        command: "/cd",
        description: "Move the session to another working directory.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: Some("path"),
    },
    CatalogSeed {
        command: "/chrome",
        description: "Configure Claude in Chrome.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/claude-api",
        description: "Load Claude API guidance or migration help.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: Some("migrate | managed-agents-onboard"),
    },
    CatalogSeed {
        command: "/clear",
        description: "Start a new conversation with empty context.",
        aliases: &["reset", "new"],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: Some("optional previous-session name"),
    },
    CatalogSeed {
        command: "/code-review",
        description: "Review the current diff for correctness and cleanup.",
        aliases: &[],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("effort, flags, or target"),
    },
    CatalogSeed {
        command: "/color",
        description: "Set the prompt bar color.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: Some("color | default"),
    },
    CatalogSeed {
        command: "/compact",
        description: "Summarize the conversation to free context space.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: Some("optional focus instructions"),
    },
    CatalogSeed {
        command: "/config",
        description: "Open or update Claude Code settings.",
        aliases: &["settings"],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: Some("key=value"),
    },
    CatalogSeed {
        command: "/context",
        description: "Visualize what is using the conversation context.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("diagnostics"),
        argument_hint: Some("all"),
    },
    CatalogSeed {
        command: "/copy",
        description: "Copy a recent assistant response or code block.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: Some("optional response number"),
    },
    CatalogSeed {
        command: "/cost",
        description: "Show session and plan usage.",
        aliases: &["usage", "stats"],
        opens_provider_menu: false,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/dataviz",
        description: "Apply chart and dashboard design guidance.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: Some("optional request"),
    },
    CatalogSeed {
        command: "/debug",
        description: "Enable debug logging and investigate a problem.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("diagnostics"),
        argument_hint: Some("optional description"),
    },
    CatalogSeed {
        command: "/deep-research",
        description: "Research a question with cross-checked web sources.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: Some("question"),
    },
    CatalogSeed {
        command: "/design-login",
        description: "Authorize Claude Design access.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/design-sync",
        description: "Upload the repository design system to Claude Design.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: Some("optional hint"),
    },
    CatalogSeed {
        command: "/desktop",
        description: "Continue the session in Claude Code Desktop.",
        aliases: &["app"],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/diff",
        description: "Open the interactive working-tree diff viewer.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/doctor",
        description: "Diagnose and optionally repair Claude Code setup.",
        aliases: &["checkup"],
        opens_provider_menu: true,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/effort",
        description: "Set the model reasoning effort level.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("model"),
        argument_hint: Some("low | medium | high | xhigh | max | auto"),
    },
    CatalogSeed {
        command: "/exit",
        description: "Exit or detach from the Claude CLI.",
        aliases: &["quit"],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/export",
        description: "Export the current conversation.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: Some("optional filename"),
    },
    CatalogSeed {
        command: "/fast",
        description: "Toggle fast mode.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("model"),
        argument_hint: Some("on | off"),
    },
    CatalogSeed {
        command: "/feedback",
        description: "Send feedback or a bug report to Anthropic.",
        aliases: &["bug", "share"],
        opens_provider_menu: true,
        category: Some("account"),
        argument_hint: Some("optional report"),
    },
    CatalogSeed {
        command: "/fewer-permission-prompts",
        description: "Build a safe allowlist from common read-only tools.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/focus",
        description: "Toggle the focused conversation view.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/fork",
        description: "Send a side directive to a forked subagent.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: Some("directive"),
    },
    CatalogSeed {
        command: "/goal",
        description: "Set, inspect, or clear a persistent goal.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: Some("condition | clear"),
    },
    CatalogSeed {
        command: "/heapdump",
        description: "Write a JavaScript heap snapshot for diagnostics.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/help",
        description: "Show help and commands.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/hooks",
        description: "View tool-event hook configuration.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/ide",
        description: "Manage IDE integrations and status.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/init",
        description: "Initialize the project with a CLAUDE.md guide.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/insights",
        description: "Analyze recent Claude Code usage and friction.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/install-github-app",
        description: "Install and configure the Claude GitHub App.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/install-slack-app",
        description: "Install the Claude Slack app.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/keybindings",
        description: "Open the keyboard shortcut configuration.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/login",
        description: "Sign in to an Anthropic account.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/logout",
        description: "Sign out of the Anthropic account.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/loop",
        description: "Run a prompt repeatedly while the session remains open.",
        aliases: &["proactive"],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("interval and prompt"),
    },
    CatalogSeed {
        command: "/mcp",
        description: "Manage MCP connections and authentication.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: Some("reconnect | enable | disable"),
    },
    CatalogSeed {
        command: "/memory",
        description: "Manage CLAUDE.md and auto-memory.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/mobile",
        description: "Show a QR code for the Claude mobile app.",
        aliases: &["ios", "android"],
        opens_provider_menu: false,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/model",
        description: "Switch the Claude model used by this session.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("model"),
        argument_hint: Some("model"),
    },
    CatalogSeed {
        command: "/passes",
        description: "Share an eligible Claude Code trial pass.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/permissions",
        description: "Manage allow, ask, and deny tool rules.",
        aliases: &["allowed-tools"],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/plan",
        description: "Enter plan mode with an optional task description.",
        aliases: &[],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("optional description"),
    },
    CatalogSeed {
        command: "/plugin",
        description: "Manage Claude Code plugins.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: Some("subcommand"),
    },
    CatalogSeed {
        command: "/powerup",
        description: "Explore Claude Code features through lessons.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/privacy-settings",
        description: "View and update privacy settings.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/radio",
        description: "Open Claude FM radio.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/recap",
        description: "Generate a one-line session recap.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/release-notes",
        description: "Browse Claude Code release notes.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/reload-plugins",
        description: "Reload active plugins without restarting.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: Some("--force"),
    },
    CatalogSeed {
        command: "/reload-skills",
        description: "Rescan skill and custom command directories.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/remote-control",
        description: "Expose this session through Claude Remote Control.",
        aliases: &["rc"],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/remote-env",
        description: "Choose the default environment for cloud agents.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/rename",
        description: "Rename the current session.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: Some("optional name"),
    },
    CatalogSeed {
        command: "/resume",
        description: "Resume a saved conversation.",
        aliases: &["continue"],
        opens_provider_menu: true,
        category: Some("session"),
        argument_hint: Some("optional session"),
    },
    CatalogSeed {
        command: "/review",
        description: "Review a GitHub pull request.",
        aliases: &[],
        opens_provider_menu: true,
        category: None,
        argument_hint: Some("optional PR"),
    },
    CatalogSeed {
        command: "/rewind",
        description: "Rewind conversation or code to a checkpoint.",
        aliases: &["checkpoint", "undo"],
        opens_provider_menu: true,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/run",
        description: "Launch and verify the project application.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/run-skill-generator",
        description: "Teach run and verify how to drive this project.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/sandbox",
        description: "Toggle sandbox mode.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/schedule",
        description: "Create and manage cloud routines.",
        aliases: &["routines"],
        opens_provider_menu: true,
        category: None,
        argument_hint: Some("optional description"),
    },
    CatalogSeed {
        command: "/scroll-speed",
        description: "Adjust fullscreen mouse-wheel scroll speed.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/security-review",
        description: "Analyze pending changes for vulnerabilities.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/setup-bedrock",
        description: "Configure Amazon Bedrock authentication.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/setup-vertex",
        description: "Configure Google Cloud model authentication.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/simplify",
        description: "Review changed code for focused cleanup.",
        aliases: &[],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("optional target"),
    },
    CatalogSeed {
        command: "/skills",
        description: "Browse and configure available skills.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/stats",
        description: "Open detailed usage statistics.",
        aliases: &["usage", "cost"],
        opens_provider_menu: true,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/status",
        description: "Show version, model, account, and connectivity.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/statusline",
        description: "Configure the terminal status line.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: Some("optional description"),
    },
    CatalogSeed {
        command: "/stickers",
        description: "Order Claude Code stickers.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/stop",
        description: "Stop the attached background session.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/tasks",
        description: "View and manage background work.",
        aliases: &["bashes"],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/team-onboarding",
        description: "Generate a team onboarding guide from usage.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/teleport",
        description: "Pull a Claude web session into this terminal.",
        aliases: &["tp"],
        opens_provider_menu: true,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/terminal-setup",
        description: "Configure terminal shortcuts.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/theme",
        description: "Choose a built-in or custom terminal theme.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/tui",
        description: "Choose the default or fullscreen terminal renderer.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: Some("default | fullscreen"),
    },
    CatalogSeed {
        command: "/ultraplan",
        description: "Draft and review a deep plan in the browser.",
        aliases: &[],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("prompt"),
    },
    CatalogSeed {
        command: "/ultrareview",
        description: "Run a deep cloud code review.",
        aliases: &[],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("optional PR"),
    },
    CatalogSeed {
        command: "/upgrade",
        description: "Open the subscription upgrade page.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/usage",
        description: "Show session cost and plan usage limits.",
        aliases: &["cost", "stats"],
        opens_provider_menu: true,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/usage-credits",
        description: "Configure usage credits and spending limits.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/verify",
        description: "Build, run, and observe a code change.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/voice",
        description: "Configure Claude voice dictation.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: Some("hold | tap | off"),
    },
    CatalogSeed {
        command: "/web-setup",
        description: "Connect GitHub credentials to Claude Code on the web.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/workflows",
        description: "View and manage workflow progress.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
];

pub const CODEX_SEEDS: &[CatalogSeed] = &[
    CatalogSeed {
        command: "/permissions",
        description: "Set what Codex may do without asking.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/ide",
        description: "Include files and selections from the IDE.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/keymap",
        description: "Inspect and remap terminal shortcuts.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/vim",
        description: "Toggle Vim editing mode.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/setup-default-sandbox",
        description: "Set up the elevated Windows sandbox.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/sandbox-add-read-dir",
        description: "Grant sandbox read access to another directory.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: Some("path"),
    },
    CatalogSeed {
        command: "/agent",
        description: "Inspect or switch agent threads.",
        aliases: &["subagents"],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/apps",
        description: "Browse apps and insert one into the prompt.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/plugins",
        description: "Browse and manage Codex plugins.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/hooks",
        description: "View and manage lifecycle hooks.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/clear",
        description: "Clear the terminal and start a new task.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/rename",
        description: "Rename the current task.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: Some("name"),
    },
    CatalogSeed {
        command: "/archive",
        description: "Archive the session and exit Codex.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/delete",
        description: "Permanently delete this session and descendants.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/compact",
        description: "Summarize the conversation to free context.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/copy",
        description: "Copy the latest completed Codex response.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/diff",
        description: "Show the complete Git working-tree diff.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/exit",
        description: "Exit the Codex CLI.",
        aliases: &["quit"],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/experimental",
        description: "Toggle experimental Codex features.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/approve",
        description: "Retry a command denied by auto review.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/memories",
        description: "Configure memory injection and generation.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/skills",
        description: "Browse and use installed skills.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/import",
        description: "Import supported Claude Code configuration.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/feedback",
        description: "Send feedback and diagnostics to OpenAI.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/init",
        description: "Generate an AGENTS.md scaffold.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/logout",
        description: "Sign out of Codex.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("account"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/mcp",
        description: "List configured MCP servers and tools.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/mention",
        description: "Attach a file or folder to the prompt.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/model",
        description: "Choose the model and reasoning effort.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("model"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/fast",
        description: "Toggle the model's Fast service tier.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("model"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/plan",
        description: "Switch to plan mode with an optional prompt.",
        aliases: &[],
        opens_provider_menu: false,
        category: None,
        argument_hint: Some("optional prompt"),
    },
    CatalogSeed {
        command: "/goal",
        description: "Set, inspect, pause, or clear a task goal.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/personality",
        description: "Choose a Codex communication style.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("model"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/ps",
        description: "Inspect background terminals and recent output.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/stop",
        description: "Stop background terminals for this session.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("tools"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/fork",
        description: "Fork this task into a new task.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/app",
        description: "Continue this session in the desktop app.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/side",
        description: "Start an ephemeral side conversation.",
        aliases: &["btw"],
        opens_provider_menu: true,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/raw",
        description: "Toggle raw scrollback mode.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/resume",
        description: "Resume a saved conversation.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/new",
        description: "Start a new conversation in this CLI session.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/quit",
        description: "Exit the Codex CLI.",
        aliases: &["exit"],
        opens_provider_menu: false,
        category: Some("session"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/review",
        description: "Review the current working tree.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("workflow"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/status",
        description: "Show model, permissions, usage, and context.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/usage",
        description: "Show token usage and rate-limit timing.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/debug-config",
        description: "Print layered configuration diagnostics.",
        aliases: &[],
        opens_provider_menu: false,
        category: Some("diagnostics"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/statusline",
        description: "Choose and order terminal footer fields.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/title",
        description: "Choose terminal title fields.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/theme",
        description: "Choose a syntax-highlighting theme.",
        aliases: &[],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
    CatalogSeed {
        command: "/pets",
        description: "Choose or hide a terminal pet.",
        aliases: &["pet"],
        opens_provider_menu: true,
        category: Some("configuration"),
        argument_hint: None,
    },
];
